alias l='ls'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias b='cd ../'
alias c='clear'
alias dir='open .'
alias emacs='emacs -nw'
alias emacsq='emacs -q --load=~/.emacs.d/inits/00-basic.el'
alias eq='emacsq'
